### ISSUE TITLE
Please change the title of codes

### ISSUE THREAD

**Issue by songsong0425** [ashertwang/CMTs-Draft#1]
Hi, while I looking at your code, some codes were hard to understand directly (e.g., dist, vht, km, mg, mvb).
Although I slightly recognized the meaning of them by the value of `target_column` in each file, can you clarify the title of the codes?
Also, please describe the order of the code processing in the README file with additional information.

**Comment by ashertwang** [comment]
Hello, apologies for the oversight. The titles of the codes are as follows:
-dist -> univariate distributions of age, weight, & survival
-hvt -> classifying healthy dogs vs. dogs with tumors (exploratory)
-km -> kaplan-meier survival time curves for each metabolic grade
-mg -> comparing metabolic grade to Pena grade
-mvb -> diagnosing malignant tumors vs. benign tumors
Could you please describe what you mean by order of code processing?

**Comment by songsong0425** [comment]
Thank you for your kind reply.
I recommend changing the code title, for example, km -> kaplan-meier_analysis; mvb -> malignant_benign_diagnosis, etc.
Do we run the code independently, or sequentially? In other words, should I run the code from dist -> hvt -> km -> mg -> mvb? If each code performs independently, please ignore this comment.

**Comment by ashertwang** [comment]
The code can be run independently as each code is associated with a separate datafile.
I have changed the code titles. Should I do the same with the datafile names?
Also, if you have any other questions, please feel free to ask.

**Comment by songsong0425** [comment]
I confirmed the changes. Thank you for your work.
In my opinion, you don't need to change the title of the data since they were clarified in the source code.
I'll close this comment.

Good luck!

PS. https://github.com/pinga-lab/paper-template will help you revise the README file.
